#!/bin/sh
#
# @name Omni Hex
#
# @type Hexarotor x
# @class Copter
#
# @maintainer Yueqian Liu
#
#

# basic mc settings
. ${R}etc/init.d/rc.mc_defaults

# EKF2 setting
param set-default EKF2_AID_MASK 280
param set-default EKF2_HGT_MODE 3
param set-default EKF2_EV_DELAY 5

# control allocation data flow
angular_velocity_controller start
control_allocator start
param set MPC_USE_HTE 0
param set COM_PREARM_MODE 0

# model ineria info
#param set-default VM_MASS 4
param set-default VM_MASS 3.81
param set-default VM_INERTIA_XX 0.0788
param set-default VM_INERTIA_YY 0.0789
param set-default VM_INERTIA_ZZ 0.1573

# position controller
param set-default MPC_XY_P 1            # 0.95
param set-default MPC_XY_VEL_P_ACC 4    # 1.8
param set-default MPC_XY_VEL_I_ACC 2    # 0.4
param set-default MPC_XY_VEL_D_ACC 0    # 0.2
#param set-default MPC_XY_VEL_MAX 100
param set-default MPC_Z_P 2             # 1
param set-default MPC_Z_VEL_P_ACC 4     # 4
param set-default MPC_Z_VEL_I_ACC 8     # 2
param set-default MPC_Z_VEL_D_ACC 0     # 0
#param set-default MPC_Z_VEL_MAX_UP 20
#param set-default MPC_Z_VEL_MAX_DN 5

# attitude controller
param set-default MC_ROLL_P 6.5         # 6.5
param set-default MC_PITCH_P 6.5        # 6.5
param set-default MC_YAW_P 2.8          # 2.8
param set-default MC_ROLLRATE_MAX 50
param set-default MC_PITCHRATE_MAX 50
param set-default MC_YAWRATE_MAX 50

# angular velocity controller settings
param set-default AVC_X_P 8             # 18
param set-default AVC_X_I 0.3           # 0.2
param set-default AVC_X_D 0.01          # 0.36
param set-default AVC_Y_P 8             # 18
param set-default AVC_Y_I 0.3           # 0.2
param set-default AVC_Y_D 0.01          # 0.36
param set-default AVC_Z_P 4             # 7
param set-default AVC_Z_I 0.3           # 0.1
param set-default AVC_Z_D 0.01          # 0

# control allocation basics
param set-default CA_AIRFRAME 3
param set-default CA_METHOD 2

param set-default CA_ACT0_MIN 0.0
param set-default CA_ACT1_MIN 0.0
param set-default CA_ACT2_MIN 0.0
param set-default CA_ACT3_MIN 0.0
param set-default CA_ACT4_MIN 0.0
param set-default CA_ACT5_MIN 0.0
param set-default CA_ACT6_MIN 0.0
param set-default CA_ACT7_MIN 0.0
param set-default CA_ACT8_MIN 0.0
param set-default CA_ACT9_MIN 0.0
param set-default CA_ACT10_MIN 0.0
param set-default CA_ACT11_MIN 0.0

param set-default CA_ACT0_MAX 1.0
param set-default CA_ACT1_MAX 1.0
param set-default CA_ACT2_MAX 1.0
param set-default CA_ACT3_MAX 1.0
param set-default CA_ACT4_MAX 1.0
param set-default CA_ACT5_MAX 1.0
param set-default CA_ACT6_MAX 1.0
param set-default CA_ACT7_MAX 1.0
param set-default CA_ACT8_MAX 1.0
param set-default CA_ACT9_MAX 1.0
param set-default CA_ACT10_MAX 1.0
param set-default CA_ACT11_MAX 1.0

# control allocation omnihex only
param set-default CA_OH_AL 0.340        # allocation matrix param
param set-default CA_OH_CT 19.125
param set-default CA_OH_KT 1.1475

param set-default CA_OH_DEBUG_EN 0      # related to servo rotation config
param set-default CA_OH_ROTATE_DIR 0
param set-default CA_OH_IS_SIM 1        # deprecated, not used anymore
param set-default CA_OH_ARM_D_MAX 0.03
param set-default CA_OH_FORCE_THR 10

param set-default CA_OH_DAMP_THR 0.3    # kinematic singularity
param set-default CA_OH_ALGN_THR 0.1

param set-default CA_OH_HANDLE_LEV 1    # some params not used anymore
param set-default CA_OH_RANK_D_THR 0.1745
param set-default CA_OH_RANK_D_ADD 0.1745
param set-default CA_OH_UNWIND_VEL 0.03

# general mixer settings
set MAV_TYPE 13
set MIXER direct
set PWM_OUT 123456
set MIXER_AUX direct_aux
set PWM_AUX_OUT 123456


# for fixed-arm + standard mixer only
# . ${R}etc/init.d/rc.mc_defaults

# param set-default MC_PITCHRATE_P 0.0800
# param set-default MC_PITCHRATE_I 0.0400
# param set-default MC_PITCHRATE_D 0.0010
# param set-default MC_PITCH_P 9.0
# param set-default MC_ROLLRATE_P 0.0800
# param set-default MC_ROLLRATE_I 0.0400
# param set-default MC_ROLLRATE_D 0.0010
# param set-default MC_ROLL_P 9.0
# param set-default MPC_XY_VEL_I_ACC 4
# param set-default MPC_XY_VEL_P_ACC 3

# param set-default RTL_DESCEND_ALT 10

# param set-default TRIG_INTERFACE 3
# param set-default TRIG_MODE 4
# param set-default MNT_MODE_IN 4
# param set-default MNT_MODE_OUT 2
# param set-default MAV_PROTO_VER 2

# set MAV_TYPE 13

# set MIXER hexa_x
